<?php

namespace Tests\Feature;

use App\Api\v1\Repositories\VoteRepository;
use App\Models\Post;
use Faker\Factory;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Symfony\Component\HttpFoundation\Response;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class VoteTest extends TestCase
{
    private $token;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutMiddleware([
            \App\Http\Middleware\Geetest::class,
            \App\Http\Middleware\Throttle::class,
        ]);

        $res = $this->post('/door/login', [
            'access' => 15958154647,
            'secret' => 'meiyoumima',
        ]);

        $this->token = $res->getOriginalContent()['data'];
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testVoteVoted()
    {
        $response = $this->json('POST', '/vote/1/user?vote_item_id=1', [], [
            'Authorization' => sprintf('Bearer %s', $this->token),
        ]);

        $response->assertStatus(Response::HTTP_CONFLICT);
    }

    public function testVote()
    {
        $faker = Factory::create();
        $vote = $this->json('POST', '/post/create', [
            'bangumiId' => 1,
            'title' => $faker->text(20),
            'desc' => $faker->text(20),
            'content' => $faker->text(20),
            'is_creator' => 1,
            'images' => [],
            'types' => Post::VOTE,
            'vote' => [
                'title' => $faker->text(20),
                'items' => [
                    [
                        'title' => $faker->text(20),
                    ],
                    [
                        'title' => $faker->text(20),
                    ],
                ],
            ]
        ], [
            'Authorization' => sprintf('Bearer %s', $this->token),
            'Content-Type' => 'application/json',
        ]);

        $postId = $vote->getOriginalContent()['data']['data'];
        $repository = new VoteRepository;
        $vote = $repository->getVoteByPostId($postId);

        $response = $this->json('POST', '/vote/' . $vote['id'] . '/user?vote_item_id=' . $vote['items'][0]['id'], [], [
            'Authorization' => sprintf('Bearer %s', $this->token),
        ]);

        $response->assertStatus(Response::HTTP_CREATED);
    }

    public function testVoteNotComfortToItem()
    {
        $response = $this->json('POST', '/vote/2/user?vote_item_id=1', [], [
            'Authorization' => sprintf('Bearer %s', $this->token),
        ]);

        $response->assertStatus(Response::HTTP_NOT_FOUND);
    }
}
